<?php /* application/views/scripts/users/edit.phtml */ ?>
 
<h1>Edi&ccedil;&atilde;o de usu&aacute;rio</h1>
 
<p>
<a href="<?php echo $this->url(array(
    'controller' => 'users',
    'action'     => 'list')); ?>" title="Listar usu&aacute;rios">Listar usu&aacute;rios</a>
</p>
 
<?php if ( isset($this->message) ) echo $this->message; ?>
 
<?php if ( isset($this->form) ) : ?>
    <?php echo $this->form; ?>
<?php endif; ?>
